### ISSUE TITLE
Error while calling Mailbox Quota

### ISSUE THREAD

**Issue by madanbisht** [davidmoten/odata-client#93]
Hi David,
   Odata library is giving below error while getting mailbox quota. Can you please take a look?

**API Call:**
res = MSGraph.reports().getMailboxUsageDetail("D7").get();

**Exception:**
_{
  "timestamp": "2020-12-26T18:27:53.465+00:00",
  "path": "/test/quota",
  "status": "BAD_REQUEST",
  "error": "Bad Request",
  "message": "responseCode=400 from url=https://graph.microsoft.com/v1.0/reports/getMailboxUsageDetail/(period%3D%22D7%22), expectedResponseCode in [200, 200], message=\n{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Resource not found for the segment 'getMailboxUsageDetail'.\",\r\n
}_

**Comment by davidmoten** [comment]
Thanks for the report. From msgraph documentation it looks like we shouldn't have that final / in the url. I'll have a look.

**Comment by davidmoten** [comment]
This is a somewhat messy one. According to https://docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-1.0 it returns a 302 redirection to a CSV file. While I ponder it I suggest you use a custom request:

```java
String csv = client._custom().getString("https://graph.microsoft.com/v1.0/reports/getMailboxUsageDetail(period%3D'D7')", RequestOptions.EMPTY);
```

**Comment by davidmoten** [comment]
I've raised this query about the strange reports metadata https://github.com/microsoftgraph/msgraph-metadata/issues/44

**Comment by davidmoten** [comment]
This is resolved in 0.1.46 available now on Maven Central. Please try it out to confirm.

**Comment by madanbisht** [comment]
Thanks David, we tried(with 0.1.46) and still getting exception(PFB) while retrieving mailboxquota, Can you please take a look?

**API call:**
_byte[] res = read(OdataClientFactory
                    .request()
                    .reports()
                    .getMailboxUsageDetail("D7")
                    .get());_

**Error:**
_{
  "timestamp": "2020-12-31T06:43:45.325+00:00",
  "path": "/test/quota",
  "status": "INTERNAL_SERVER_ERROR",
  "error": "Internal Server Error",
  "message": "javax.net.ssl.SSLException: Connection has closed: javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify",
  "requestId": "a4a4bcf9-1",
  "statusCode": 500
}_
	
**Stack trace:**
		_at com.github.davidmoten.odata.client.internal.Util.read(Util.java:103) ~[odata-client-runtime-0.1.46.jar:na]
		at com.org.mailServ.(Quota.java:70) ~[classes/:na]
		at com.org.orgHandler(Quota.java:34) ~[classes/:na]
		at org.springframework.web.reactive.function.server.support.HandlerFunctionAdapter.handle(HandlerFunctionAdapter.java:61) ~[spring-webflux-5.2.9.RELEASE.jar:5.2.9.RELEASE]
		at org.springframework.web.reactive.DispatcherHandler.invokeHandler(DispatcherHandler.java:161) ~[spring-webflux-5.2.9.RELEASE.jar:5.2.9.RELEASE]
		at org.springframework.web.reactive.DispatcherHandler.lambda$handle$1(DispatcherHandler.java:146) ~[spring-webflux-5.2.9.RELEASE.jar:5.2.9.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]_

**Comment by davidmoten** [comment]
Hmm, "internal server error" doesn't look like a problem with the library. Can you do a test just from a main method without all the spring and reactor stuff? Can you try other reports to see if they have the same behaviour (from an isolated main method would be best).

**Comment by davidmoten** [comment]
This could be a hint for me: https://stackoverflow.com/questions/63466356/javax-net-ssl-sslexception-closing-inbound-before-receiving-peers-close-notify

**Comment by madanbisht** [comment]
Sure we will check and JFYI below query also gives the same exception:

String csv = client._custom().getString("https://graph.microsoft.com/v1.0/reports/getMailboxUsageDetail(period%3D'D7')", RequestOptions.EMPTY);

**Comment by davidmoten** [comment]
nice, thanks. I see the problem. Will be fixed soon.

**Comment by davidmoten** [comment]
Should be fixed now in 0.1.47 on Maven Central now. Please try it out.

Sorry about that problem. I refactored the stream processing a fair bit and I don't have a unit test for it. I'll ponder creating one.

**Comment by madanbisht** [comment]
Thank you, its working fine with version 0.1.47

**Comment by madanbisht** [comment]
Hi David,
As per microsoft documentation, '[Get mailbox detail](https://docs.microsoft.com/en-us/graph/api/resources/mailbox-usage-reports?view=graph-rest-1.0)' is a stream API. Can we use the below  Odata API as stream?

```
OdataClientFactory
                    .request()
                    .reports()
                    .getMailboxUsageDetail("D7")
                    .get();
```

**Comment by davidmoten** [comment]
.get returns an InputStream doesn't it?

**Comment by madanbisht** [comment]
Apologize for the delay, Yes it has inputStream, Thanks for clarification.
